name: Failure Notification

on:
  push:

jobs:
  failing-job:
    runs-on: ubuntu-latest
    steps:
    - name: failing step
      run: exit 1
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ always() && (needs.failing-job.result == 'failure' || needs.failing-job.result == 'timed_out') }}
    needs:
      - failing-job
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        MSG_MINIMAL: actions_url
        SLACK_FOOTER: ""
        SLACK_TITLE: LSST metadetect tests failing on lsst-dev
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
